### ISSUE TITLE
Failure to build on powerpc64le

### ISSUE THREAD

**Issue by daxtens** [technion/ruby-argon2#10]
Hi,

Attempting to install argon2 on powerpc64le fails as follows:

```
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.10
Successfully installed ffi-compiler-0.1.3
Building native extensions.  This could take a while...
ERROR:  Error installing argon2:
        ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20160226-63-1rv0m7c.rb extconf.rb

make "DESTDIR=" clean
rm -f tests libargon2_wrap.so

make "DESTDIR="
cc -std=c89 -pthread -O3 -Wall -g -march=native -shared -fPIC ../phc-winner-argon2/src/argon2.c ../phc-winner-argon2/src/core.c ../phc-winner-argon2/src/blake2/blake2b.c ../phc-winner-argon2/src/thread.c ../phc-winner-argon2/src/encoding.c argon_wrap.c ../phc-winner-argon2/src/opt.c -o libargon2_wrap.so
cc: error: unrecognized command line option '-march=native'
Makefile:54: recipe for target 'libs' failed
make: *** [libs] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.2/gems/argon2-0.1.4 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.2/extensions/powerpc64le-linux/2.2.0/argon2-0.1.4/gem_make.out
```

This seems to be caused by powerpc gcc not supporting `-march`. We have `-mcpu` and friends, but it's probably easiest if you just drop the flag on powerpc.

Thanks in advance!

**Comment by technion** [comment]
Hi,

Thanks for bringing this issue to our attention.

As this relates to compiling the C library, can you test if the C reference library compiles on your machine when built with optimisations?

    git clone https://github.com/P-H-C/phc-winner-argon2/
    OPT=TRUE make

If that fails, we will need to address it there.

**Comment by technion** [comment]
Having just tested this, yes, the reference library will build with -march, as this is required for the optimisations, and there are no platform 

I'm reluctant to diverge from the mainline strategy, and far more reluctant to introduce code changes for the sake of obscure hardware that nobody actually runs in production servers.

**Comment by daxtens** [comment]
Hi. Thanks for looking into this. Thanks for the information about the upstream project: I'll follow it up with them.

**Comment by technion** [comment]
As this has been accepted upstream, I have pulled in a fix in the master branch. I will tag 1.0 shortly.
