### ISSUE TITLE
change in api breaks other gems

### ISSUE THREAD

**Issue by rojoko** [technion/ruby-argon2#13]
The change in the api to create a password from version 0.1.4 to 1.0.0 in https://github.com/technion/ruby-argon2/blob/master/lib/argon2.rb from #hash to #create breaks the devise-argon2 gem https://github.com/erdostom/devise-argon2/issues/3 .

**Comment by rojoko** [comment]
I read up now why you changed the API ( https://github.com/technion/ruby-argon2/issues/9 ) and I hope the devise-argon2 will include your changed API.

**Comment by technion** [comment]
Hi Rojoko,

I would encourage any dependant gem to correctly use configure those dependencies around semantic versioning, so that breaking changes moving from 0.1.4 to 1.0.0 don't automatically propagate upwards.

I would also urge you to review this statement in the README in relation

    It is strongly advised to avoid implementations that utilise off-spec methods of introducing salts, invent imaginary parameters, or which use the word "encryption" in describing the password hashing process
