### ISSUE TITLE
Ship a new version?

### ISSUE THREAD

**Issue by siepkes** [technion/ruby-argon2#17]
Hi! I noticed that the current version of this Gem doesn't build on SmartOS (a Solaris derivative). This is because support for SmartOS / Solaris was added on 28th of may in 2016 (See: https://github.com/P-H-C/phc-winner-argon2/blob/master/Makefile#L88 ) and version 1.1.1 of the gem uses an april 2016 version of Argon2. Could I tempt you to make a 1.1.2 release? I'll buy you a beer for it if your ever in Rotterdam ;-)

**Comment by technion** [comment]
Disclaimer: I don't have a SmartOS or Solaris system around to test this with.

No problems at all, tag has been pushed. Thanks for bringing this to my attention.

**Comment by siepkes** [comment]
@technion Thanks for your quick response!
