### ISSUE TITLE
Required Ruby Version unclear based on gemspec

### ISSUE THREAD

**Issue by tenshiAMD** [technion/ruby-argon2#35]
Greetings @technion! I've just started using this gem but I noticed that the `required_ruby_version` is not defined in the `gemspec` file of this gem. It is better to indicate it so we know about its compatibility scope. Thanks~!

**Comment by technion** [comment]
I don't invest time testing on EoL versions of Ruby, so I hadn't documented without a definitive answer. I know initial versions tested against Ruby 2.2 and I doubt I broke that, however as that's listed as currently unsupported and you've wanted a definite answer I've specified 2.5.8 as required. This will push shortly.

**Comment by tenshiAMD** [comment]
@technion please let us know when you will be releasing a new version with these changes so we can update your gem on our end. Thanks, man~!

**Comment by tenshiAMD** [comment]
@technion I see the builds got broken when you specified ruby version with `~> 2.5.8` since in the travis test you include and `2.6.0` and `2.7.1`. I hope do not mind if I do PR to fix it, right?

**Comment by technion** [comment]
Awesome. I should have just left this thing out.

Feel free to create a CR fix.
