### ISSUE TITLE
RubyGems and Github naming mismatch

### ISSUE THREAD

**Issue by mensfeld** [technion/ruby-argon2#41]
Hey,

My name is Maciej Mensfeld and I run a research security project called [diffend.io.](https://diffend.io.)

I've noticed, that you have a mismatch between the repo name on GitHub (ruby-argon2) and the RubyGems one (argon2). This mismatch has been recently used as a brandjacking base for popular libraries like yours thus I took courtesy and "booked" it for you (if you want). If not, I'll just keep it as it is, protecting the argon2 :)

If you want to transfer the ownership just please reach out to me.

Have a great day and thank you 

ref https://rubygems.org/gems/ruby-argon2 https://rubygems.org/gems/argon2

**Comment by technion** [comment]
- I don't feel it's useful to name every single Ruby gem ruby-thingy
- In most circumstances I would have named the Github repo "Argon2", but then that's an official C project and nearly language has its own bindings. I don't feel a world where Rust Argon2, Javascript Argon2, etc all get a Github repo named "Argon2".

Hence here we are. Thanks for being proactive in registering potential brand jacking.

**Comment by mensfeld** [comment]
:wave: @technion I agree with your arguments.

I opened this issue just to make you aware that I "booked" this name to prevent this type of thing for this particular case and to let you know, that if you would need it, all you need to do is just ping me.

Have a great day.
