### ISSUE TITLE
legacy.rb test unused and in broken state

### ISSUE THREAD

**Issue by athix** [technion/ruby-argon2#45]
Currently the legacy test isn't included in the minitest suite due to lacking the `_test` suffix. Additionally, if you add the suffix and run the tests, it appears to be in a failing state due to a missing constant:

```shell
  1) Error:
Legacy#test_legacy_hashes:
NameError: uninitialized constant Legacy::PASS

  2) Error:
Legacy#test_valid_hash_legacy_hashes:
NameError: uninitialized constant Legacy::PASS
```

Are these tests obsolete / ready to be removed entirely?

**Comment by technion** [comment]
This is a valid test for legacy hashes. The broken filename meant it didn't detect the missing constant. I've pushed a fix for this.

**Comment by athix** [comment]
Thanks for the quick fix @technion!
