### ISSUE TITLE
Github Org for improved SEO

### ISSUE THREAD

**Issue by athix** [technion/ruby-argon2#46]
Hi @technion,

Would you be okay with moving the repo location for this to an organization? For example:

* `ruby-argon2/argon2` or
* `ruby-argon2/ruby-argon2`

Similar to [bcrypt-ruby](https://github.com/bcrypt-ruby), this would give better SEO for users trying to find the official ruby binding for Argon2, and allow you to take on more maintainers easily in the future if you choose to do so.

You should be able to create an organization, then transfer the repo to your new organization without much trouble. Github automatically redirects the current repo and all issues/PRs to the new location if you use their transfer feature.

**Comment by technion** [comment]
As a security library I don't intend on making handing over control "for improved SEO".

**Comment by athix** [comment]
@technion I think you misunderstand what I'm suggesting. This would be your organization, with you as the sole member and owner/creator. Who would you be "handing over control" to except yourself?

For example, I created [Aeon Splice](https://github.com/aeonsplice) a while back for managing my repos related to a game I'm making, and I am the only person with access/control over the organization.

`ruby-argon2` would have you, and you alone, on it if that's how you want to keep things.

It would be functionally equivalent to the setup you have now, just with a better name and more flexibility on permission controls.

(fyi, I'm not on the `bcrypt-ruby` group either.)
