### ISSUE TITLE
RBS issue - Cannot find type `FFI::Library`

### ISSUE THREAD

**Issue by TastyPi** [technion/ruby-argon2#59]
I'm exploring using RBS and Steep with our project, but ran into an issue when running `steep check`:

```
../.local/share/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/argon2-2.2.0/sig/ffi.rbs:4:4: [error] Cannot find type `FFI::Library`
│ Diagnostic ID: RBS::UnknownTypeName
│
└     extend FFI::Library
      ~~~~~~~~~~~~~~~~~~~
```

Admittedly being new to these tools I don't know if this an issue with `argon2` or `ffi`, but I thought I'd start here since the file it complains about is from this gem.

**Comment by technion** [comment]
Thanks TastyPi. To be honest I'm regretting the time spent on these tools - I figured they'd become widespread when they were announced, but I've seen very little use elsewhere and the type checks have broken several times with version updates when the rest of the library stayed functional.

I'll look into this and see what comes of it.
