### ISSUE TITLE
Default argon2.online builds a hash which ruby_argon2 cant verify

### ISSUE THREAD

**Issue by womblep** [technion/ruby-argon2#64]
If I use https://argon2.online and leave the defaults with a random salt, the generated hash wont be verified correctly by ruby_argon2.

>> require 'argon2'
=> true
>> puts Argon2::VERSION
2.3.0
=> nil
>> hash = '$argon2id$v=19$m=16,t=2,p=1$eXJ0MEtzMDlBMEpGU09MTg$T+6VYkPNTviOIOGoi8RZZA'
=> "$argon2id$v=19$m=16,t=2,p=1$eXJ0MEtzMDlBMEpGU09MTg$T+6VYkPNTviOIOGoi8RZZA"
>> Argon2::Password.verify_password('password', hash)
=> false

![image](https://github.com/technion/ruby-argon2/assets/20149897/24626283-6968-453a-b6fd-3f0eec383ea4)

If I change the hash length to 32 it works correctly.
I changed the other parameters and that didn't seem to make any difference, just the hash length.

**Comment by technion** [comment]
I've looked around and I can't see any reference to using 16 byte hashes in production - 32 is the common recommendation and I don't see a reason to try and reduce that.

I can see how ideally this would "just work", but interop with random websites isn't a goal at this time. I'm generally expecting any use case for verifying a password with this library to involve creating it with this library.

**Comment by nekogami** [comment]
@technion Hi, just a quick comment 3 years later but, one reason for giving that option of setting the hash length is that other implementation actually gives it. for example golang.org/x/crypto/argon2 allows for a custom hash length.

It would be great if we could create/verify password in a compatible way with other libraries / already generated data. would be useful for various case imo.
